name: 'Sina News Feed Bot'

on:
  push:
    branches:
      - main
  schedule:
    - cron: ' 5 * * * * '

jobs:
  feed-processor:
    name: Sina news feed processor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Build RSS
        run: node index.js
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN}}
          publish_dir: ./dist # The folder the action should deploy.
          commit_message: ${{ github.event.head_commit.message }}

